/**
 * VAPID key handling for web push.
 *
 * "Failed to execute 'subscribe' on 'PushManager': The provided
 * applicationServerKey is not valid" is the browser's single response to every
 * possible problem with this value, which makes it almost impossible to debug
 * from the message alone. The causes, in rough order of likelihood:
 *
 *   • quotes or whitespace pasted around the value in the hosting dashboard
 *   • the PRIVATE key pasted where the public one belongs
 *   • a truncated or re-wrapped key
 *   • standard base64 where base64url was required
 *
 * A valid VAPID public key is a base64url-encoded uncompressed P-256 point:
 * exactly 65 bytes, the first of which is 0x04. That is enough to tell the
 * cases apart and say something useful instead.
 */

const raw = ((import.meta as any).env?.VITE_VAPID_PUBLIC_KEY ?? "") as string;

/** Quotes and stray whitespace are the most common paste damage. */
const cleaned = String(raw)
  .trim()
  .replace(/^["']|["']$/g, "")
  .replace(/\s+/g, "");

/** base64url → bytes. Tolerates missing padding and standard-base64 characters. */
export function decodeVapidKey(value: string): Uint8Array {
  const padded = value + "=".repeat((4 - (value.length % 4)) % 4);
  const base64 = padded.replace(/-/g, "+").replace(/_/g, "/");
  const binary = window.atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

/** null when the key is usable, otherwise a sentence explaining what is wrong. */
export function vapidKeyProblem(): string | null {
  if (!cleaned) {
    return "No push key is set. Add VITE_VAPID_PUBLIC_KEY in Vercel, then redeploy.";
  }

  let bytes: Uint8Array;
  try {
    bytes = decodeVapidKey(cleaned);
  } catch {
    return "The push key is not valid base64. Copy the public key again, with no line breaks.";
  }

  // A VAPID private key is 32 bytes (43 base64url characters) and is very
  // easy to grab by mistake, so name that case specifically.
  if (bytes.length === 32) {
    return "That is the VAPID private key. The app needs the public key — the longer of the pair. The private key belongs in Supabase.";
  }

  if (bytes.length !== 65) {
    return `The push key decodes to ${bytes.length} bytes; a valid one is 65. It looks truncated or partly copied.`;
  }

  if (bytes[0] !== 0x04) {
    return "The push key is the right length but the wrong format. It should be an uncompressed P-256 key generated by web-push.";
  }

  return null;
}

/** The key as bytes, or undefined when it is unusable. */
export function vapidApplicationServerKey(): Uint8Array | undefined {
  if (vapidKeyProblem()) return undefined;
  return decodeVapidKey(cleaned);
}
