/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppZerohubRouteImport } from './routes/app.zerohub'
import { Route as AppZeroAiRouteImport } from './routes/app.zero-ai'
import { Route as AppTutorStudioRouteImport } from './routes/app.tutor-studio'
import { Route as AppStoreRouteImport } from './routes/app.store'
import { Route as AppShipRouteImport } from './routes/app.ship'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppQuestsRouteImport } from './routes/app.quests'
import { Route as AppPremiumRouteImport } from './routes/app.premium'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppInstitutionStudioRouteImport } from './routes/app.institution-studio'
import { Route as AppDraftsRouteImport } from './routes/app.drafts'
import { Route as AppComposeRouteImport } from './routes/app.compose'
import { Route as AppBoostRouteImport } from './routes/app.boost'
import { Route as AppBookmarksRouteImport } from './routes/app.bookmarks'
import { Route as AppWalletIndexRouteImport } from './routes/app.wallet.index'
import { Route as AppTutorStudioIndexRouteImport } from './routes/app.tutor-studio.index'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppProfileIndexRouteImport } from './routes/app.profile.index'
import { Route as AppNotesIndexRouteImport } from './routes/app.notes.index'
import { Route as AppInstitutionStudioIndexRouteImport } from './routes/app.institution-studio.index'
import { Route as AppClubsIndexRouteImport } from './routes/app.clubs.index'
import { Route as AppChatIndexRouteImport } from './routes/app.chat.index'
import { Route as AppBootcampsIndexRouteImport } from './routes/app.bootcamps.index'
import { Route as AppWalletWithdrawRouteImport } from './routes/app.wallet.withdraw'
import { Route as AppWalletSettingsRouteImport } from './routes/app.wallet.settings'
import { Route as AppWalletSendRouteImport } from './routes/app.wallet.send'
import { Route as AppWalletAddMoneyRouteImport } from './routes/app.wallet.add-money'
import { Route as AppTutorStudioCreateRouteImport } from './routes/app.tutor-studio.create'
import { Route as AppSettingsSecurityRouteImport } from './routes/app.settings.security'
import { Route as AppSettingsResourcesRouteImport } from './routes/app.settings.resources'
import { Route as AppSettingsPrivacyRouteImport } from './routes/app.settings.privacy'
import { Route as AppSettingsPremiumRouteImport } from './routes/app.settings.premium'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app.settings.notifications'
import { Route as AppSettingsAccountRouteImport } from './routes/app.settings.account'
import { Route as AppSettingsAccessibilityRouteImport } from './routes/app.settings.accessibility'
import { Route as AppProfileEditRouteImport } from './routes/app.profile.edit'
import { Route as AppProfileIdRouteImport } from './routes/app.profile.$id'
import { Route as AppPostIdRouteImport } from './routes/app.post.$id'
import { Route as AppNotesCreateRouteImport } from './routes/app.notes.create'
import { Route as AppNotesIdRouteImport } from './routes/app.notes.$id'
import { Route as AppLiveClassIdRouteImport } from './routes/app.live.$classId'
import { Route as AppClubsChatRouteImport } from './routes/app.clubs.chat'
import { Route as AppChatSettingsRouteImport } from './routes/app.chat.settings'
import { Route as AppChatNewRouteImport } from './routes/app.chat.new'
import { Route as AppChatIdRouteImport } from './routes/app.chat.$id'
import { Route as AppBootcampsIdRouteImport } from './routes/app.bootcamps.$id'
import { Route as AppSettingsPremiumFeaturesRouteImport } from './routes/app.settings.premium.features'
import { Route as AppProfileIdNetworkRouteImport } from './routes/app.profile_.$id.network'
import { Route as AppNotesIdEditRouteImport } from './routes/app.notes.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppZerohubRoute = AppZerohubRouteImport.update({
  id: '/zerohub',
  path: '/zerohub',
  getParentRoute: () => AppRoute,
} as any)
const AppZeroAiRoute = AppZeroAiRouteImport.update({
  id: '/zero-ai',
  path: '/zero-ai',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorStudioRoute = AppTutorStudioRouteImport.update({
  id: '/tutor-studio',
  path: '/tutor-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppShipRoute = AppShipRouteImport.update({
  id: '/ship',
  path: '/ship',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsRoute = AppQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutionStudioRoute = AppInstitutionStudioRouteImport.update({
  id: '/institution-studio',
  path: '/institution-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppDraftsRoute = AppDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppComposeRoute = AppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppRoute,
} as any)
const AppBoostRoute = AppBoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletIndexRoute = AppWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorStudioIndexRoute = AppTutorStudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTutorStudioRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppInstitutionStudioIndexRoute =
  AppInstitutionStudioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppInstitutionStudioRoute,
  } as any)
const AppClubsIndexRoute = AppClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppBootcampsIndexRoute = AppBootcampsIndexRouteImport.update({
  id: '/bootcamps/',
  path: '/bootcamps/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletWithdrawRoute = AppWalletWithdrawRouteImport.update({
  id: '/wallet/withdraw',
  path: '/wallet/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletSettingsRoute = AppWalletSettingsRouteImport.update({
  id: '/wallet/settings',
  path: '/wallet/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletSendRoute = AppWalletSendRouteImport.update({
  id: '/wallet/send',
  path: '/wallet/send',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletAddMoneyRoute = AppWalletAddMoneyRouteImport.update({
  id: '/wallet/add-money',
  path: '/wallet/add-money',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorStudioCreateRoute = AppTutorStudioCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppTutorStudioRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsResourcesRoute = AppSettingsResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPrivacyRoute = AppSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPremiumRoute = AppSettingsPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccessibilityRoute =
  AppSettingsAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPostIdRoute = AppPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesCreateRoute = AppNotesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppNotesIdRoute = AppNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppLiveClassIdRoute = AppLiveClassIdRouteImport.update({
  id: '/live/$classId',
  path: '/live/$classId',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsChatRoute = AppClubsChatRouteImport.update({
  id: '/clubs/chat',
  path: '/clubs/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppChatSettingsRoute = AppChatSettingsRouteImport.update({
  id: '/chat/settings',
  path: '/chat/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppChatNewRoute = AppChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBootcampsIdRoute = AppBootcampsIdRouteImport.update({
  id: '/bootcamps/$id',
  path: '/bootcamps/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPremiumFeaturesRoute =
  AppSettingsPremiumFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => AppSettingsPremiumRoute,
  } as any)
const AppProfileIdNetworkRoute = AppProfileIdNetworkRouteImport.update({
  id: '/profile_/$id/network',
  path: '/profile/$id/network',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIdEditRoute = AppNotesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppNotesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/boost': typeof AppBoostRoute
  '/app/compose': typeof AppComposeRoute
  '/app/drafts': typeof AppDraftsRoute
  '/app/institution-studio': typeof AppInstitutionStudioRouteWithChildren
  '/app/notes': typeof AppNotesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/quests': typeof AppQuestsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/ship': typeof AppShipRoute
  '/app/store': typeof AppStoreRoute
  '/app/tutor-studio': typeof AppTutorStudioRouteWithChildren
  '/app/zero-ai': typeof AppZeroAiRoute
  '/app/zerohub': typeof AppZerohubRoute
  '/app/': typeof AppIndexRoute
  '/app/bootcamps/$id': typeof AppBootcampsIdRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/chat/new': typeof AppChatNewRoute
  '/app/chat/settings': typeof AppChatSettingsRoute
  '/app/clubs/chat': typeof AppClubsChatRoute
  '/app/live/$classId': typeof AppLiveClassIdRoute
  '/app/notes/$id': typeof AppNotesIdRouteWithChildren
  '/app/notes/create': typeof AppNotesCreateRoute
  '/app/post/$id': typeof AppPostIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/settings/accessibility': typeof AppSettingsAccessibilityRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/premium': typeof AppSettingsPremiumRouteWithChildren
  '/app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/app/settings/resources': typeof AppSettingsResourcesRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/tutor-studio/create': typeof AppTutorStudioCreateRoute
  '/app/wallet/add-money': typeof AppWalletAddMoneyRoute
  '/app/wallet/send': typeof AppWalletSendRoute
  '/app/wallet/settings': typeof AppWalletSettingsRoute
  '/app/wallet/withdraw': typeof AppWalletWithdrawRoute
  '/app/bootcamps/': typeof AppBootcampsIndexRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/clubs/': typeof AppClubsIndexRoute
  '/app/institution-studio/': typeof AppInstitutionStudioIndexRoute
  '/app/notes/': typeof AppNotesIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tutor-studio/': typeof AppTutorStudioIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
  '/app/notes/$id/edit': typeof AppNotesIdEditRoute
  '/app/profile/$id/network': typeof AppProfileIdNetworkRoute
  '/app/settings/premium/features': typeof AppSettingsPremiumFeaturesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/boost': typeof AppBoostRoute
  '/app/compose': typeof AppComposeRoute
  '/app/drafts': typeof AppDraftsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/quests': typeof AppQuestsRoute
  '/app/ship': typeof AppShipRoute
  '/app/store': typeof AppStoreRoute
  '/app/zero-ai': typeof AppZeroAiRoute
  '/app/zerohub': typeof AppZerohubRoute
  '/app': typeof AppIndexRoute
  '/app/bootcamps/$id': typeof AppBootcampsIdRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/chat/new': typeof AppChatNewRoute
  '/app/chat/settings': typeof AppChatSettingsRoute
  '/app/clubs/chat': typeof AppClubsChatRoute
  '/app/live/$classId': typeof AppLiveClassIdRoute
  '/app/notes/$id': typeof AppNotesIdRouteWithChildren
  '/app/notes/create': typeof AppNotesCreateRoute
  '/app/post/$id': typeof AppPostIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/settings/accessibility': typeof AppSettingsAccessibilityRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/premium': typeof AppSettingsPremiumRouteWithChildren
  '/app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/app/settings/resources': typeof AppSettingsResourcesRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/tutor-studio/create': typeof AppTutorStudioCreateRoute
  '/app/wallet/add-money': typeof AppWalletAddMoneyRoute
  '/app/wallet/send': typeof AppWalletSendRoute
  '/app/wallet/settings': typeof AppWalletSettingsRoute
  '/app/wallet/withdraw': typeof AppWalletWithdrawRoute
  '/app/bootcamps': typeof AppBootcampsIndexRoute
  '/app/chat': typeof AppChatIndexRoute
  '/app/clubs': typeof AppClubsIndexRoute
  '/app/institution-studio': typeof AppInstitutionStudioIndexRoute
  '/app/notes': typeof AppNotesIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/tutor-studio': typeof AppTutorStudioIndexRoute
  '/app/wallet': typeof AppWalletIndexRoute
  '/app/notes/$id/edit': typeof AppNotesIdEditRoute
  '/app/profile/$id/network': typeof AppProfileIdNetworkRoute
  '/app/settings/premium/features': typeof AppSettingsPremiumFeaturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/boost': typeof AppBoostRoute
  '/app/compose': typeof AppComposeRoute
  '/app/drafts': typeof AppDraftsRoute
  '/app/institution-studio': typeof AppInstitutionStudioRouteWithChildren
  '/app/notes': typeof AppNotesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/quests': typeof AppQuestsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/ship': typeof AppShipRoute
  '/app/store': typeof AppStoreRoute
  '/app/tutor-studio': typeof AppTutorStudioRouteWithChildren
  '/app/zero-ai': typeof AppZeroAiRoute
  '/app/zerohub': typeof AppZerohubRoute
  '/app/': typeof AppIndexRoute
  '/app/bootcamps/$id': typeof AppBootcampsIdRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/chat/new': typeof AppChatNewRoute
  '/app/chat/settings': typeof AppChatSettingsRoute
  '/app/clubs/chat': typeof AppClubsChatRoute
  '/app/live/$classId': typeof AppLiveClassIdRoute
  '/app/notes/$id': typeof AppNotesIdRouteWithChildren
  '/app/notes/create': typeof AppNotesCreateRoute
  '/app/post/$id': typeof AppPostIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/settings/accessibility': typeof AppSettingsAccessibilityRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/premium': typeof AppSettingsPremiumRouteWithChildren
  '/app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/app/settings/resources': typeof AppSettingsResourcesRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/tutor-studio/create': typeof AppTutorStudioCreateRoute
  '/app/wallet/add-money': typeof AppWalletAddMoneyRoute
  '/app/wallet/send': typeof AppWalletSendRoute
  '/app/wallet/settings': typeof AppWalletSettingsRoute
  '/app/wallet/withdraw': typeof AppWalletWithdrawRoute
  '/app/bootcamps/': typeof AppBootcampsIndexRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/clubs/': typeof AppClubsIndexRoute
  '/app/institution-studio/': typeof AppInstitutionStudioIndexRoute
  '/app/notes/': typeof AppNotesIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tutor-studio/': typeof AppTutorStudioIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
  '/app/notes/$id/edit': typeof AppNotesIdEditRoute
  '/app/profile_/$id/network': typeof AppProfileIdNetworkRoute
  '/app/settings/premium/features': typeof AppSettingsPremiumFeaturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/signin'
    | '/signup'
    | '/app/bookmarks'
    | '/app/boost'
    | '/app/compose'
    | '/app/drafts'
    | '/app/institution-studio'
    | '/app/notes'
    | '/app/notifications'
    | '/app/premium'
    | '/app/quests'
    | '/app/settings'
    | '/app/ship'
    | '/app/store'
    | '/app/tutor-studio'
    | '/app/zero-ai'
    | '/app/zerohub'
    | '/app/'
    | '/app/bootcamps/$id'
    | '/app/chat/$id'
    | '/app/chat/new'
    | '/app/chat/settings'
    | '/app/clubs/chat'
    | '/app/live/$classId'
    | '/app/notes/$id'
    | '/app/notes/create'
    | '/app/post/$id'
    | '/app/profile/$id'
    | '/app/profile/edit'
    | '/app/settings/accessibility'
    | '/app/settings/account'
    | '/app/settings/notifications'
    | '/app/settings/premium'
    | '/app/settings/privacy'
    | '/app/settings/resources'
    | '/app/settings/security'
    | '/app/tutor-studio/create'
    | '/app/wallet/add-money'
    | '/app/wallet/send'
    | '/app/wallet/settings'
    | '/app/wallet/withdraw'
    | '/app/bootcamps/'
    | '/app/chat/'
    | '/app/clubs/'
    | '/app/institution-studio/'
    | '/app/notes/'
    | '/app/profile/'
    | '/app/settings/'
    | '/app/tutor-studio/'
    | '/app/wallet/'
    | '/app/notes/$id/edit'
    | '/app/profile/$id/network'
    | '/app/settings/premium/features'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/app/bookmarks'
    | '/app/boost'
    | '/app/compose'
    | '/app/drafts'
    | '/app/notifications'
    | '/app/premium'
    | '/app/quests'
    | '/app/ship'
    | '/app/store'
    | '/app/zero-ai'
    | '/app/zerohub'
    | '/app'
    | '/app/bootcamps/$id'
    | '/app/chat/$id'
    | '/app/chat/new'
    | '/app/chat/settings'
    | '/app/clubs/chat'
    | '/app/live/$classId'
    | '/app/notes/$id'
    | '/app/notes/create'
    | '/app/post/$id'
    | '/app/profile/$id'
    | '/app/profile/edit'
    | '/app/settings/accessibility'
    | '/app/settings/account'
    | '/app/settings/notifications'
    | '/app/settings/premium'
    | '/app/settings/privacy'
    | '/app/settings/resources'
    | '/app/settings/security'
    | '/app/tutor-studio/create'
    | '/app/wallet/add-money'
    | '/app/wallet/send'
    | '/app/wallet/settings'
    | '/app/wallet/withdraw'
    | '/app/bootcamps'
    | '/app/chat'
    | '/app/clubs'
    | '/app/institution-studio'
    | '/app/notes'
    | '/app/profile'
    | '/app/settings'
    | '/app/tutor-studio'
    | '/app/wallet'
    | '/app/notes/$id/edit'
    | '/app/profile/$id/network'
    | '/app/settings/premium/features'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/signin'
    | '/signup'
    | '/app/bookmarks'
    | '/app/boost'
    | '/app/compose'
    | '/app/drafts'
    | '/app/institution-studio'
    | '/app/notes'
    | '/app/notifications'
    | '/app/premium'
    | '/app/quests'
    | '/app/settings'
    | '/app/ship'
    | '/app/store'
    | '/app/tutor-studio'
    | '/app/zero-ai'
    | '/app/zerohub'
    | '/app/'
    | '/app/bootcamps/$id'
    | '/app/chat/$id'
    | '/app/chat/new'
    | '/app/chat/settings'
    | '/app/clubs/chat'
    | '/app/live/$classId'
    | '/app/notes/$id'
    | '/app/notes/create'
    | '/app/post/$id'
    | '/app/profile/$id'
    | '/app/profile/edit'
    | '/app/settings/accessibility'
    | '/app/settings/account'
    | '/app/settings/notifications'
    | '/app/settings/premium'
    | '/app/settings/privacy'
    | '/app/settings/resources'
    | '/app/settings/security'
    | '/app/tutor-studio/create'
    | '/app/wallet/add-money'
    | '/app/wallet/send'
    | '/app/wallet/settings'
    | '/app/wallet/withdraw'
    | '/app/bootcamps/'
    | '/app/chat/'
    | '/app/clubs/'
    | '/app/institution-studio/'
    | '/app/notes/'
    | '/app/profile/'
    | '/app/settings/'
    | '/app/tutor-studio/'
    | '/app/wallet/'
    | '/app/notes/$id/edit'
    | '/app/profile_/$id/network'
    | '/app/settings/premium/features'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/zerohub': {
      id: '/app/zerohub'
      path: '/zerohub'
      fullPath: '/app/zerohub'
      preLoaderRoute: typeof AppZerohubRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/zero-ai': {
      id: '/app/zero-ai'
      path: '/zero-ai'
      fullPath: '/app/zero-ai'
      preLoaderRoute: typeof AppZeroAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tutor-studio': {
      id: '/app/tutor-studio'
      path: '/tutor-studio'
      fullPath: '/app/tutor-studio'
      preLoaderRoute: typeof AppTutorStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ship': {
      id: '/app/ship'
      path: '/ship'
      fullPath: '/app/ship'
      preLoaderRoute: typeof AppShipRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quests': {
      id: '/app/quests'
      path: '/quests'
      fullPath: '/app/quests'
      preLoaderRoute: typeof AppQuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/institution-studio': {
      id: '/app/institution-studio'
      path: '/institution-studio'
      fullPath: '/app/institution-studio'
      preLoaderRoute: typeof AppInstitutionStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drafts': {
      id: '/app/drafts'
      path: '/drafts'
      fullPath: '/app/drafts'
      preLoaderRoute: typeof AppDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compose': {
      id: '/app/compose'
      path: '/compose'
      fullPath: '/app/compose'
      preLoaderRoute: typeof AppComposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/boost': {
      id: '/app/boost'
      path: '/boost'
      fullPath: '/app/boost'
      preLoaderRoute: typeof AppBoostRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookmarks': {
      id: '/app/bookmarks'
      path: '/bookmarks'
      fullPath: '/app/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/': {
      id: '/app/wallet/'
      path: '/wallet'
      fullPath: '/app/wallet/'
      preLoaderRoute: typeof AppWalletIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tutor-studio/': {
      id: '/app/tutor-studio/'
      path: '/'
      fullPath: '/app/tutor-studio/'
      preLoaderRoute: typeof AppTutorStudioIndexRouteImport
      parentRoute: typeof AppTutorStudioRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes/': {
      id: '/app/notes/'
      path: '/'
      fullPath: '/app/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/app/institution-studio/': {
      id: '/app/institution-studio/'
      path: '/'
      fullPath: '/app/institution-studio/'
      preLoaderRoute: typeof AppInstitutionStudioIndexRouteImport
      parentRoute: typeof AppInstitutionStudioRoute
    }
    '/app/clubs/': {
      id: '/app/clubs/'
      path: '/clubs'
      fullPath: '/app/clubs/'
      preLoaderRoute: typeof AppClubsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bootcamps/': {
      id: '/app/bootcamps/'
      path: '/bootcamps'
      fullPath: '/app/bootcamps/'
      preLoaderRoute: typeof AppBootcampsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/withdraw': {
      id: '/app/wallet/withdraw'
      path: '/wallet/withdraw'
      fullPath: '/app/wallet/withdraw'
      preLoaderRoute: typeof AppWalletWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/settings': {
      id: '/app/wallet/settings'
      path: '/wallet/settings'
      fullPath: '/app/wallet/settings'
      preLoaderRoute: typeof AppWalletSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/send': {
      id: '/app/wallet/send'
      path: '/wallet/send'
      fullPath: '/app/wallet/send'
      preLoaderRoute: typeof AppWalletSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/add-money': {
      id: '/app/wallet/add-money'
      path: '/wallet/add-money'
      fullPath: '/app/wallet/add-money'
      preLoaderRoute: typeof AppWalletAddMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tutor-studio/create': {
      id: '/app/tutor-studio/create'
      path: '/create'
      fullPath: '/app/tutor-studio/create'
      preLoaderRoute: typeof AppTutorStudioCreateRouteImport
      parentRoute: typeof AppTutorStudioRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/resources': {
      id: '/app/settings/resources'
      path: '/resources'
      fullPath: '/app/settings/resources'
      preLoaderRoute: typeof AppSettingsResourcesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/privacy': {
      id: '/app/settings/privacy'
      path: '/privacy'
      fullPath: '/app/settings/privacy'
      preLoaderRoute: typeof AppSettingsPrivacyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/premium': {
      id: '/app/settings/premium'
      path: '/premium'
      fullPath: '/app/settings/premium'
      preLoaderRoute: typeof AppSettingsPremiumRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/account': {
      id: '/app/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/accessibility': {
      id: '/app/settings/accessibility'
      path: '/accessibility'
      fullPath: '/app/settings/accessibility'
      preLoaderRoute: typeof AppSettingsAccessibilityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/$id': {
      id: '/app/profile/$id'
      path: '/profile/$id'
      fullPath: '/app/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/post/$id': {
      id: '/app/post/$id'
      path: '/post/$id'
      fullPath: '/app/post/$id'
      preLoaderRoute: typeof AppPostIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes/create': {
      id: '/app/notes/create'
      path: '/create'
      fullPath: '/app/notes/create'
      preLoaderRoute: typeof AppNotesCreateRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/app/notes/$id': {
      id: '/app/notes/$id'
      path: '/$id'
      fullPath: '/app/notes/$id'
      preLoaderRoute: typeof AppNotesIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/app/live/$classId': {
      id: '/app/live/$classId'
      path: '/live/$classId'
      fullPath: '/app/live/$classId'
      preLoaderRoute: typeof AppLiveClassIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/chat': {
      id: '/app/clubs/chat'
      path: '/clubs/chat'
      fullPath: '/app/clubs/chat'
      preLoaderRoute: typeof AppClubsChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/settings': {
      id: '/app/chat/settings'
      path: '/chat/settings'
      fullPath: '/app/chat/settings'
      preLoaderRoute: typeof AppChatSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/new': {
      id: '/app/chat/new'
      path: '/chat/new'
      fullPath: '/app/chat/new'
      preLoaderRoute: typeof AppChatNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bootcamps/$id': {
      id: '/app/bootcamps/$id'
      path: '/bootcamps/$id'
      fullPath: '/app/bootcamps/$id'
      preLoaderRoute: typeof AppBootcampsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/premium/features': {
      id: '/app/settings/premium/features'
      path: '/features'
      fullPath: '/app/settings/premium/features'
      preLoaderRoute: typeof AppSettingsPremiumFeaturesRouteImport
      parentRoute: typeof AppSettingsPremiumRoute
    }
    '/app/profile_/$id/network': {
      id: '/app/profile_/$id/network'
      path: '/profile/$id/network'
      fullPath: '/app/profile/$id/network'
      preLoaderRoute: typeof AppProfileIdNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes/$id/edit': {
      id: '/app/notes/$id/edit'
      path: '/edit'
      fullPath: '/app/notes/$id/edit'
      preLoaderRoute: typeof AppNotesIdEditRouteImport
      parentRoute: typeof AppNotesIdRoute
    }
  }
}

interface AppInstitutionStudioRouteChildren {
  AppInstitutionStudioIndexRoute: typeof AppInstitutionStudioIndexRoute
}

const AppInstitutionStudioRouteChildren: AppInstitutionStudioRouteChildren = {
  AppInstitutionStudioIndexRoute: AppInstitutionStudioIndexRoute,
}

const AppInstitutionStudioRouteWithChildren =
  AppInstitutionStudioRoute._addFileChildren(AppInstitutionStudioRouteChildren)

interface AppNotesIdRouteChildren {
  AppNotesIdEditRoute: typeof AppNotesIdEditRoute
}

const AppNotesIdRouteChildren: AppNotesIdRouteChildren = {
  AppNotesIdEditRoute: AppNotesIdEditRoute,
}

const AppNotesIdRouteWithChildren = AppNotesIdRoute._addFileChildren(
  AppNotesIdRouteChildren,
)

interface AppNotesRouteChildren {
  AppNotesIdRoute: typeof AppNotesIdRouteWithChildren
  AppNotesCreateRoute: typeof AppNotesCreateRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesIdRoute: AppNotesIdRouteWithChildren,
  AppNotesCreateRoute: AppNotesCreateRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppSettingsPremiumRouteChildren {
  AppSettingsPremiumFeaturesRoute: typeof AppSettingsPremiumFeaturesRoute
}

const AppSettingsPremiumRouteChildren: AppSettingsPremiumRouteChildren = {
  AppSettingsPremiumFeaturesRoute: AppSettingsPremiumFeaturesRoute,
}

const AppSettingsPremiumRouteWithChildren =
  AppSettingsPremiumRoute._addFileChildren(AppSettingsPremiumRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAccessibilityRoute: typeof AppSettingsAccessibilityRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsPremiumRoute: typeof AppSettingsPremiumRouteWithChildren
  AppSettingsPrivacyRoute: typeof AppSettingsPrivacyRoute
  AppSettingsResourcesRoute: typeof AppSettingsResourcesRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccessibilityRoute: AppSettingsAccessibilityRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsPremiumRoute: AppSettingsPremiumRouteWithChildren,
  AppSettingsPrivacyRoute: AppSettingsPrivacyRoute,
  AppSettingsResourcesRoute: AppSettingsResourcesRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppTutorStudioRouteChildren {
  AppTutorStudioCreateRoute: typeof AppTutorStudioCreateRoute
  AppTutorStudioIndexRoute: typeof AppTutorStudioIndexRoute
}

const AppTutorStudioRouteChildren: AppTutorStudioRouteChildren = {
  AppTutorStudioCreateRoute: AppTutorStudioCreateRoute,
  AppTutorStudioIndexRoute: AppTutorStudioIndexRoute,
}

const AppTutorStudioRouteWithChildren = AppTutorStudioRoute._addFileChildren(
  AppTutorStudioRouteChildren,
)

interface AppRouteChildren {
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppBoostRoute: typeof AppBoostRoute
  AppComposeRoute: typeof AppComposeRoute
  AppDraftsRoute: typeof AppDraftsRoute
  AppInstitutionStudioRoute: typeof AppInstitutionStudioRouteWithChildren
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppQuestsRoute: typeof AppQuestsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppShipRoute: typeof AppShipRoute
  AppStoreRoute: typeof AppStoreRoute
  AppTutorStudioRoute: typeof AppTutorStudioRouteWithChildren
  AppZeroAiRoute: typeof AppZeroAiRoute
  AppZerohubRoute: typeof AppZerohubRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBootcampsIdRoute: typeof AppBootcampsIdRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppChatNewRoute: typeof AppChatNewRoute
  AppChatSettingsRoute: typeof AppChatSettingsRoute
  AppClubsChatRoute: typeof AppClubsChatRoute
  AppLiveClassIdRoute: typeof AppLiveClassIdRoute
  AppPostIdRoute: typeof AppPostIdRoute
  AppProfileIdRoute: typeof AppProfileIdRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppWalletAddMoneyRoute: typeof AppWalletAddMoneyRoute
  AppWalletSendRoute: typeof AppWalletSendRoute
  AppWalletSettingsRoute: typeof AppWalletSettingsRoute
  AppWalletWithdrawRoute: typeof AppWalletWithdrawRoute
  AppBootcampsIndexRoute: typeof AppBootcampsIndexRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppClubsIndexRoute: typeof AppClubsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppWalletIndexRoute: typeof AppWalletIndexRoute
  AppProfileIdNetworkRoute: typeof AppProfileIdNetworkRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookmarksRoute: AppBookmarksRoute,
  AppBoostRoute: AppBoostRoute,
  AppComposeRoute: AppComposeRoute,
  AppDraftsRoute: AppDraftsRoute,
  AppInstitutionStudioRoute: AppInstitutionStudioRouteWithChildren,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppQuestsRoute: AppQuestsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppShipRoute: AppShipRoute,
  AppStoreRoute: AppStoreRoute,
  AppTutorStudioRoute: AppTutorStudioRouteWithChildren,
  AppZeroAiRoute: AppZeroAiRoute,
  AppZerohubRoute: AppZerohubRoute,
  AppIndexRoute: AppIndexRoute,
  AppBootcampsIdRoute: AppBootcampsIdRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppChatNewRoute: AppChatNewRoute,
  AppChatSettingsRoute: AppChatSettingsRoute,
  AppClubsChatRoute: AppClubsChatRoute,
  AppLiveClassIdRoute: AppLiveClassIdRoute,
  AppPostIdRoute: AppPostIdRoute,
  AppProfileIdRoute: AppProfileIdRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppWalletAddMoneyRoute: AppWalletAddMoneyRoute,
  AppWalletSendRoute: AppWalletSendRoute,
  AppWalletSettingsRoute: AppWalletSettingsRoute,
  AppWalletWithdrawRoute: AppWalletWithdrawRoute,
  AppBootcampsIndexRoute: AppBootcampsIndexRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppClubsIndexRoute: AppClubsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppWalletIndexRoute: AppWalletIndexRoute,
  AppProfileIdNetworkRoute: AppProfileIdNetworkRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
