/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppTutorStudioRouteImport } from './routes/app.tutor-studio'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPremiumRouteImport } from './routes/app.premium'
import { Route as AppClubsRouteImport } from './routes/app.clubs'
import { Route as AppBootcampsRouteImport } from './routes/app.bootcamps'
import { Route as AppBookmarksRouteImport } from './routes/app.bookmarks'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorStudioRoute = AppTutorStudioRouteImport.update({
  id: '/tutor-studio',
  path: '/tutor-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsRoute = AppClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AppRoute,
} as any)
const AppBootcampsRoute = AppBootcampsRouteImport.update({
  id: '/bootcamps',
  path: '/bootcamps',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/bootcamps': typeof AppBootcampsRoute
  '/app/clubs': typeof AppClubsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tutor-studio': typeof AppTutorStudioRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/bootcamps': typeof AppBootcampsRoute
  '/app/clubs': typeof AppClubsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tutor-studio': typeof AppTutorStudioRoute
  '/app/wallet': typeof AppWalletRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/bootcamps': typeof AppBootcampsRoute
  '/app/clubs': typeof AppClubsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tutor-studio': typeof AppTutorStudioRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/bookmarks'
    | '/app/bootcamps'
    | '/app/clubs'
    | '/app/premium'
    | '/app/profile'
    | '/app/tutor-studio'
    | '/app/wallet'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/bookmarks'
    | '/app/bootcamps'
    | '/app/clubs'
    | '/app/premium'
    | '/app/profile'
    | '/app/tutor-studio'
    | '/app/wallet'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/bookmarks'
    | '/app/bootcamps'
    | '/app/clubs'
    | '/app/premium'
    | '/app/profile'
    | '/app/tutor-studio'
    | '/app/wallet'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tutor-studio': {
      id: '/app/tutor-studio'
      path: '/tutor-studio'
      fullPath: '/app/tutor-studio'
      preLoaderRoute: typeof AppTutorStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs': {
      id: '/app/clubs'
      path: '/clubs'
      fullPath: '/app/clubs'
      preLoaderRoute: typeof AppClubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bootcamps': {
      id: '/app/bootcamps'
      path: '/bootcamps'
      fullPath: '/app/bootcamps'
      preLoaderRoute: typeof AppBootcampsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookmarks': {
      id: '/app/bookmarks'
      path: '/bookmarks'
      fullPath: '/app/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppBootcampsRoute: typeof AppBootcampsRoute
  AppClubsRoute: typeof AppClubsRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTutorStudioRoute: typeof AppTutorStudioRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookmarksRoute: AppBookmarksRoute,
  AppBootcampsRoute: AppBootcampsRoute,
  AppClubsRoute: AppClubsRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppProfileRoute: AppProfileRoute,
  AppTutorStudioRoute: AppTutorStudioRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
