/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Automatically precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Clean old caches
cleanupOutdatedCaches();

/*
 * A new version waits rather than seizing the open page.
 *
 * This used to call self.skipWaiting() unconditionally at the top level. The
 * effect, combined with registerType: "autoUpdate", was that every time the
 * app regained focus the browser revalidated the service worker, and if
 * anything had been deployed since, the new worker activated immediately,
 * claimed the running page, and the injected registration reloaded it. Anyone
 * who switched to their bank app and came back lost their place.
 *
 * Waiting means the update applies on the next cold start instead, which for
 * a phone app is soon enough. clientsClaim still runs so the very first
 * install controls the page without needing a reload, and the ChunkLoadError
 * handler in __root.tsx already covers the one case where a stale page really
 * must refresh: a code chunk that no longer exists on the server.
 */
clientsClaim();

// Left as an explicit opt-in, so an update can still be applied on demand
// (post {type: 'SKIP_WAITING'}) without any background reload.
self.addEventListener('message', (event) => {
  if ((event.data as any)?.type === 'SKIP_WAITING') self.skipWaiting();
});

/*
 * Runtime caching. Precaching alone only covers build output; these rules make
 * repeat navigations, images and fonts fast, and keep the app usable when the
 * network drops. Live data (Supabase, server functions) is deliberately never
 * cached so members always see current information.
 */

// Pages: fast when online, still render from cache when offline.
registerRoute(
  new NavigationRoute(
    new NetworkFirst({
      cacheName: 'zc-pages',
      // Short: past this the cached page shows at once and the fresh one is
      // saved for next time. 4s left phones staring at a blank screen.
      networkTimeoutSeconds: 2,
      plugins: [new ExpirationPlugin({ maxEntries: 40, maxAgeSeconds: 60 * 60 * 24 * 7 })],
    }),
    { denylist: [/^\/api\//, /^\/_serverFn/] },
  ),
);

// Content-hashed build assets never change, so cache-first is always correct.
registerRoute(
  ({ url, request }) =>
    url.origin === self.location.origin &&
    (url.pathname.startsWith('/assets/') || request.destination === 'script' || request.destination === 'style'),
  new CacheFirst({
    cacheName: 'zc-assets',
    plugins: [new ExpirationPlugin({ maxEntries: 120, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  }),
);

// Google Fonts stylesheet: from cache on every launch after the first.
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'zc-font-css',
    plugins: [new ExpirationPlugin({ maxEntries: 8, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  }),
);

// Images and fonts: show instantly from cache, refresh quietly in the background.
registerRoute(
  ({ request }) => request.destination === 'image' || request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: 'zc-media',
    plugins: [new ExpirationPlugin({ maxEntries: 80, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  }),
);

// Handle incoming push events from the OS
self.addEventListener('push', (event) => {
  let payload: any = {
    title: 'Zero Club',
    body: 'You have a new notification',
    url: '/app/notifications',
  };

  try {
    if (event.data) {
      payload = event.data.json();
    }
  } catch (err) {
    if (event.data) {
      payload.body = event.data.text();
    }
  }

  const options: NotificationOptions & {
    vibrate?: number[];
    actions?: { action: string; title: string; icon?: string }[];
    renotify?: boolean;
  } = {
    body: payload.body,
    // The sender's photo for messages, like chat apps; the app icon otherwise.
    icon: payload.icon || '/icons/icon-192.png',
    // Android's status bar draws the badge as a white silhouette, so it
    // needs the monochrome icon (a full-colour logo shows as a white square).
    badge: '/icons/icon-monochrome-512.png',
    vibrate: payload.type === 'game_buzz' ? [250, 80, 250, 80, 400] : [100, 50, 100],
    requireInteraction: payload.type === 'game_buzz',
    // One notification per conversation that updates as new messages arrive,
    // and still buzzes each time (renotify), the way WhatsApp behaves.
    tag: payload.type === 'game_buzz' ? `zero-game-buzz:${payload.url || ''}` : payload.tag || undefined,
    renotify: payload.type === 'game_buzz' || Boolean(payload.tag),
    data: {
      url: payload.url || '/app',
    },
    actions: [
      {
        action: 'open',
        title: payload.type === 'game_buzz' ? 'Join game' : 'Open App'
      }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(payload.title || 'Zero Club', options)
  );
});

// Handle user clicking the notification: open exactly what it was about.
//
// This used to call client.navigate() without waiting for it. navigate() only
// works on a page this worker controls, and throws otherwise, so a tap often
// just brought the app forward wherever it already was instead of opening the
// chat. Now the running app is asked to route there itself (instant, no
// reload), with a full navigation and then a new window as fallbacks.
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const target = new URL(event.notification.data?.url || '/app', self.location.origin).href;

  const askAppToRoute = (client: WindowClient) =>
    new Promise<boolean>((resolve) => {
      const channel = new MessageChannel();
      const timer = setTimeout(() => resolve(false), 1500);
      channel.port1.onmessage = () => {
        clearTimeout(timer);
        resolve(true);
      };
      client.postMessage({ type: 'NOTIFICATION_NAVIGATE', url: target }, [channel.port2]);
    });

  event.waitUntil((async () => {
    const windows = (await self.clients.matchAll({ type: 'window', includeUncontrolled: true })) as WindowClient[];
    const sameOrigin = windows.filter((c) => new URL(c.url).origin === self.location.origin);
    // Prefer the window the person was last looking at.
    const client = sameOrigin.find((c) => c.focused) || sameOrigin.find((c) => c.visibilityState === 'visible') || sameOrigin[0];

    if (client) {
      // Focus first, while the tap still counts as a user gesture.
      const focused = await client.focus().catch(() => client);
      if (await askAppToRoute(focused)) return;
      try {
        if (await focused.navigate(target)) return;
      } catch {
        /* Not controlled by this worker; open a fresh window instead. */
      }
    }

    await self.clients.openWindow(target);
  })());
});

