/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Automatically precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Clean old caches
cleanupOutdatedCaches();

// Take control of all pages immediately
self.skipWaiting();
clientsClaim();

/*
 * Runtime caching. Precaching alone only covers build output; these rules make
 * repeat navigations, images and fonts fast, and keep the app usable when the
 * network drops. Live data (Supabase, server functions) is deliberately never
 * cached so members always see current information.
 */

// Pages: fast when online, still render from cache when offline.
registerRoute(
  new NavigationRoute(
    new NetworkFirst({
      cacheName: 'zc-pages',
      networkTimeoutSeconds: 4,
      plugins: [new ExpirationPlugin({ maxEntries: 40, maxAgeSeconds: 60 * 60 * 24 * 7 })],
    }),
    { denylist: [/^\/api\//, /^\/_serverFn/] },
  ),
);

// Content-hashed build assets never change, so cache-first is always correct.
registerRoute(
  ({ url, request }) =>
    url.origin === self.location.origin &&
    (url.pathname.startsWith('/assets/') || request.destination === 'script' || request.destination === 'style'),
  new CacheFirst({
    cacheName: 'zc-assets',
    plugins: [new ExpirationPlugin({ maxEntries: 120, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  }),
);

// Images and fonts: show instantly from cache, refresh quietly in the background.
registerRoute(
  ({ request }) => request.destination === 'image' || request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: 'zc-media',
    plugins: [new ExpirationPlugin({ maxEntries: 80, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  }),
);

// Handle incoming push events from the OS
self.addEventListener('push', (event) => {
  let payload: any = {
    title: 'Zero Club',
    body: 'You have a new notification',
    url: '/app/notifications',
  };

  try {
    if (event.data) {
      payload = event.data.json();
    }
  } catch (err) {
    if (event.data) {
      payload.body = event.data.text();
    }
  }

  const options: NotificationOptions & {
    vibrate?: number[];
    actions?: { action: string; title: string; icon?: string }[];
    renotify?: boolean;
  } = {
    body: payload.body,
    icon: '/logo.png', // Uses your app icon
    badge: '/logo.png', // Small monochrome icon for Android status bar
    vibrate: payload.type === 'game_buzz' ? [250, 80, 250, 80, 400] : [100, 50, 100],
    requireInteraction: payload.type === 'game_buzz',
    tag: payload.type === 'game_buzz' ? `zero-game-buzz:${payload.url || ''}` : undefined,
    renotify: payload.type === 'game_buzz',
    data: {
      url: payload.url || '/app',
    },
    actions: [
      {
        action: 'open',
        title: payload.type === 'game_buzz' ? 'Join game' : 'Open App'
      }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(payload.title || 'Zero Club', options)
  );
});

// Handle user clicking the notification
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const targetUrl = event.notification.data?.url || '/app';

  // Check if we already have a window open to the app
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // If there is an existing window, navigate it to the URL and focus
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url.includes(self.registration.scope) && 'focus' in client) {
          client.navigate(targetUrl);
          return client.focus();
        }
      }
      // If no window exists, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});
