/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// Automatically precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Clean old caches
cleanupOutdatedCaches();

// Take control of all pages immediately
self.skipWaiting();
clientsClaim();

// Handle incoming push events from the OS
self.addEventListener('push', (event) => {
  let payload: any = {
    title: 'Zero Club',
    body: 'You have a new notification',
    url: '/app/notifications',
  };

  try {
    if (event.data) {
      payload = event.data.json();
    }
  } catch (err) {
    if (event.data) {
      payload.body = event.data.text();
    }
  }

  const options: NotificationOptions = {
    body: payload.body,
    icon: '/logo.png', // Uses your app icon
    badge: '/logo.png', // Small monochrome icon for Android status bar
    vibrate: [100, 50, 100],
    data: {
      url: payload.url || '/app',
    },
    actions: [
      {
        action: 'open',
        title: 'Open App'
      }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(payload.title || 'Zero Club', options)
  );
});

// Handle user clicking the notification
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const targetUrl = event.notification.data?.url || '/app';

  // Check if we already have a window open to the app
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // If there is an existing window, navigate it to the URL and focus
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url.includes(self.registration.scope) && 'focus' in client) {
          client.navigate(targetUrl);
          return client.focus();
        }
      }
      // If no window exists, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl);
      }
    })
  );
});
