-- Zero Form: allow choice-style questions.
--
-- zero_form_fields.field_type was limited to seven input types, all of which
-- collect a single free-text or single-select value. Form builders expect the
-- Tally/Google Forms set, so this adds:
--
--   multiple_choice  pick exactly one from a visible list (radio buttons)
--   checkboxes       pick any number from a list, stored as a JSON array
--   yes_no           a two-option shorthand, kept distinct from a dropdown so
--                    the builder can render it without asking for options
--   file_upload      reserved. Accepted by the database now so the constraint
--                    does not need changing again, but not yet offered in the
--                    builder: it needs a storage bucket and size limits first.
--
-- The three types users already know by other names are unchanged:
--   short answer -> text, long answer -> textarea, dropdown -> select.
--
-- Existing rows are unaffected: every current value stays valid, so this
-- widens the constraint rather than replacing it.

-- The original constraint was declared inline, so its name was generated by
-- Postgres and may differ between environments. Find it by definition rather
-- than assuming a name.
do $$
declare
  existing_constraint text;
begin
  select con.conname
    into existing_constraint
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace nsp on nsp.oid = rel.relnamespace
  where nsp.nspname = 'public'
    and rel.relname = 'zero_form_fields'
    and con.contype = 'c'
    and pg_get_constraintdef(con.oid) ilike '%field_type%'
  limit 1;

  if existing_constraint is not null then
    execute format(
      'alter table public.zero_form_fields drop constraint %I',
      existing_constraint
    );
  end if;
end $$;

-- Re-add with an explicit name so future migrations can target it directly.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'zero_form_fields_field_type_check'
  ) then
    alter table public.zero_form_fields
      add constraint zero_form_fields_field_type_check
      check (field_type in (
        'text',
        'email',
        'phone',
        'number',
        'textarea',
        'select',
        'country',
        'multiple_choice',
        'checkboxes',
        'yes_no',
        'file_upload'
      ));
  end if;
end $$;

comment on column public.zero_form_fields.options is
  'Choice list for select, multiple_choice and checkboxes. A JSON array of '
  'strings. Ignored by every other field type. yes_no needs no options: the '
  'form renders Yes and No itself.';
